name: FISCO-BCOS GitHub Actions
on:
  push:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]
env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build_with_clang:
    name: build_with_clang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: check commit
        if: ${{ runner.os == 'Linux' && github.base_ref != 'master' && github.event_name == 'pull_request' }}
        run: bash bcos-cmake-scripts/shell/check-commit.sh 3000 "https://api.github.com/repos/FISCO-BCOS/bcos-tars-protocol"
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.hunter
          key: deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-
            deps-v0-${{ runner.temp }}-
      - uses: actions/cache@v2
        id: ccache
        with:
          path: ccache
          key: ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-
            ccache-v0-${{ runner.temp }}-
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install ccache
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt install -y git curl build-essential clang cmake ccache
      - name: configure
        run: CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake . -DTESTS=ON
      - name: compile
        run: make -j2
      - name: run test
        run: make test
  build_with_gcc:
    name: build_with_gcc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.hunter
          key: deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-
            deps-v0-${{ runner.temp }}-
      - uses: actions/cache@v2
        id: ccache
        with:
          path: ccache
          key: ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-
            ccache-v0-${{ runner.temp }}-
      - name: install Ubuntu dependencies
        run: sudo apt install -y git curl build-essential cmake ccache
      - name: configure
        run: cmake . -DTESTS=ON
      - name: compile
        run: make -j2
      - name: run test
        run: make test        
  ubuntu16_04_build_with_gcc:
    name: ubuntu16_04_build_with_gcc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.hunter
          key: deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-
            deps-v0-${{ runner.temp }}-
      - uses: actions/cache@v2
        id: ccache
        with:
          path: ccache
          key: ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-
            ccache-v0-${{ runner.temp }}-
      - name: install Ubuntu dependencies
        run: sudo apt-get install -y software-properties-common python-software-properties && sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt install -y git curl build-essential cmake ccache gcc-7 g++-7 lcov&& sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 && sudo update-alternatives --config gcc
      - name: configure
        run: cmake . -DTESTS=ON -DCOVERAGE=ON
      - name: compile
        run: make -j2
      - name: run test
        run: make test
      - name: generate coverage
        run: make coverage
      - name: upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.info
          name: bcos-tars-protocol coverage
          fail_ci_if_error: true
  build_with_centos:
    name: build_with_centos
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/.hunter
          key: deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-v0-${{ runner.temp }}-${{ github.base_ref }}-
            deps-v0-${{ runner.temp }}-
      - uses: actions/cache@v2
        id: ccache
        with:
          path: ccache
          key: ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            ccache-v0-${{ runner.temp }}-${{ github.base_ref }}-
            ccache-v0-${{ runner.temp }}-
      - name: install CentOS dependencies
        run: |
          yum install -y epel-release centos-release-scl
          yum install -y git make gcc gcc-c++ glibc-static glibc-devel cmake3 ccache devtoolset-7 && source /opt/rh/devtoolset-7/enable
      - name: configure and compile
        run: |
          source /opt/rh/devtoolset-7/enable
          mkdir -p build && cd build
          cmake3 .. -DTESTS=ON
          make -j2
          make test